apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/idey/tekton-reversewords:7e7dff898c83fcf22dc5611975ccaedf3aa74af6
        name: reverse-words
