namespace: reverse-words-stage
commonLabels:
  app: reversewords-stage
bases:
- github.com/cloudapps-idey/reverse-words-cicd?ref=config
resources:
- namespace.yaml
- ingress.yaml
patchesStrategicMerge:
- deployment.yaml

